/* ==========================================================================
   WORD QUEST RUN — 語彙データ（コア）

   ライセンス:
   著作権者は浅井。本プロジェクトのために新規作成した専有データ（All rights reserved）。
   自作データは自動的にCC0にはならないため、CC0相当とは表記しない。
   市販辞書・Web辞書・権利不明のデータは一切含まない。ShareAlike 義務なし。
   詳細と台帳は docs/VOCAB_LICENSES.md（DS-001）を正とする。

   圧縮形式（モバイルの転送量を抑えるため配列で持つ）:
   [ 0:英単語, 1:日本語訳, 2:品詞, 3:難易度, 4:カテゴリ, 5:発音, 6:例文, 7:例文訳 ]

   品詞 pos: n=名詞 / v=動詞 / adj=形容詞 / adv=副詞
   難易度 lvl: 1=Starter 2=Basic 3=Intermediate 4=Advanced 5=Expert 6=Master

   カテゴリは「誤答を意味的に紛らわしくする」ために使う。
   同じ品詞・近い難易度・同じか隣接カテゴリから誤答を選ぶことで、
   「apple の誤答が 走る／静かな」のような品詞不一致を構造的に不可能にする。
   ========================================================================== */
window.VOCAB_META = {
  version: '1.0.0',
  license: 'Proprietary (All rights reserved). Authored for WORD QUEST RUN.',
  copyright: '浅井 / WORD QUEST RUN',
  shareAlike: false,
  attributionRequired: false,
  ledger: 'docs/VOCAB_LICENSES.md#DS-001',
  sources: [
    { id: 'DS-001', name: 'WORD QUEST RUN original vocabulary',
      copyrightHolder: '浅井', origin: 'newly authored for this project',
      license: 'Proprietary (All rights reserved)', acquiredOn: '2026-07-28/29',
      modifications: 'none (original work)', attribution: 'not required',
      shareAlike: false, inAppNotice: 'credits screen only', words: 'all' }
  ],
  fields: ['w', 'ja', 'pos', 'lvl', 'cat', 'ipa', 'ex', 'exJa']
};

window.VOCAB_RAW = [
/* ── 名詞: 食べ物 ─────────────────────────────────────────── */
["apple","りんご","n",1,"food","/ˈæp.əl/","I eat an apple every morning.","毎朝りんごを食べます。"],
["bread","パン","n",1,"food","/bred/","She bought fresh bread.","彼女は焼きたてのパンを買った。"],
["rice","米","n",1,"food","/raɪs/","Rice is a staple food here.","ここでは米が主食です。"],
["meat","肉","n",1,"food","/miːt/","He does not eat meat.","彼は肉を食べない。"],
["fish","魚","n",1,"food","/fɪʃ/","We had fish for dinner.","夕食に魚を食べた。"],
["egg","卵","n",1,"food","/eɡ/","Boil the egg for ten minutes.","卵を10分ゆでてください。"],
["milk","牛乳","n",1,"food","/mɪlk/","Please buy some milk.","牛乳を買ってきて。"],
["water","水","n",1,"food","/ˈwɔː.tər/","Please drink some water.","水を飲んでください。"],
["salt","塩","n",2,"food","/sɔːlt/","Add a little salt.","塩を少し加えて。"],
["sugar","砂糖","n",2,"food","/ˈʃʊɡ.ər/","I take my coffee without sugar.","コーヒーは砂糖なしで飲みます。"],
["soup","スープ","n",2,"food","/suːp/","The soup is still hot.","スープはまだ熱い。"],
["fruit","果物","n",2,"food","/fruːt/","Eat more fruit.","もっと果物を食べなさい。"],
["vegetable","野菜","n",2,"food","/ˈvedʒ.tə.bəl/","Vegetables are good for you.","野菜は体に良い。"],
["meal","食事","n",2,"food","/miːl/","We had a quiet meal.","静かな食事をとった。"],
["dish","料理","n",3,"food","/dɪʃ/","This dish is famous here.","この料理はここの名物だ。"],
["recipe","レシピ","n",3,"food","/ˈres.ɪ.pi/","She shared her recipe.","彼女はレシピを教えてくれた。"],
["flavor","風味","n",4,"food","/ˈfleɪ.vər/","The soup has a rich flavor.","そのスープは風味が豊かだ。"],
["ingredient","材料","n",4,"food","/ɪnˈɡriː.di.ənt/","List every ingredient.","材料をすべて書き出して。"],
["nutrition","栄養","n",4,"food","/njuːˈtrɪʃ.ən/","Nutrition matters for growth.","成長には栄養が重要だ。"],

/* ── 名詞: 自然 ─────────────────────────────────────────── */
["sun","太陽","n",1,"nature","/sʌn/","The sun is bright today.","今日は太陽がまぶしい。"],
["moon","月","n",1,"nature","/muːn/","The moon is full tonight.","今夜は満月だ。"],
["star","星","n",1,"nature","/stɑːr/","Stars filled the sky.","星が空を埋めていた。"],
["sky","空","n",1,"nature","/skaɪ/","The sky turned red.","空が赤くなった。"],
["sea","海","n",1,"nature","/siː/","The sea was calm.","海は穏やかだった。"],
["river","川","n",1,"nature","/ˈrɪv.ər/","We crossed the river.","私たちは川を渡った。"],
["mountain","山","n",1,"nature","/ˈmaʊn.tɪn/","The mountain is covered in snow.","その山は雪に覆われている。"],
["forest","森","n",2,"nature","/ˈfɒr.ɪst/","A path led into the forest.","小道が森へ続いていた。"],
["tree","木","n",1,"nature","/triː/","A tall tree stood there.","高い木が立っていた。"],
["flower","花","n",1,"nature","/ˈflaʊ.ər/","She picked a flower.","彼女は花を摘んだ。"],
["stone","石","n",2,"nature","/stəʊn/","He threw a stone.","彼は石を投げた。"],
["wind","風","n",2,"nature","/wɪnd/","The wind grew stronger.","風が強くなった。"],
["rain","雨","n",1,"nature","/reɪn/","The rain stopped at noon.","雨は昼に止んだ。"],
["snow","雪","n",1,"nature","/snəʊ/","Snow covered the road.","雪が道を覆った。"],
["cloud","雲","n",2,"nature","/klaʊd/","A dark cloud appeared.","黒い雲が現れた。"],
["island","島","n",2,"nature","/ˈaɪ.lənd/","They live on a small island.","彼らは小さな島に住んでいる。"],
["valley","谷","n",3,"nature","/ˈvæl.i/","The valley was full of mist.","谷は霧で満ちていた。"],
["desert","砂漠","n",3,"nature","/ˈdez.ət/","The desert is silent at night.","夜の砂漠は静かだ。"],
["climate","気候","n",4,"nature","/ˈklaɪ.mət/","The climate is changing.","気候が変わりつつある。"],
["horizon","地平線","n",4,"nature","/həˈraɪ.zən/","The sun sank below the horizon.","太陽が地平線に沈んだ。"],

/* ── 名詞: 人・関係 ─────────────────────────────────────── */
["friend","友達","n",1,"people","/frend/","He is my best friend.","彼は私の親友だ。"],
["family","家族","n",1,"people","/ˈfæm.əl.i/","My family lives nearby.","家族は近くに住んでいる。"],
["child","子ども","n",1,"people","/tʃaɪld/","The child was laughing.","その子どもは笑っていた。"],
["parent","親","n",2,"people","/ˈpeə.rənt/","Every parent worries.","親は誰でも心配する。"],
["teacher","先生","n",1,"people","/ˈtiː.tʃər/","Our teacher is kind.","先生は優しい。"],
["student","学生","n",1,"people","/ˈstjuː.dənt/","She is a hard-working student.","彼女は勤勉な学生だ。"],
["doctor","医者","n",1,"people","/ˈdɒk.tər/","Call a doctor at once.","すぐに医者を呼んで。"],
["neighbor","隣人","n",2,"people","/ˈneɪ.bər/","Our neighbor is quiet.","隣人は静かな人だ。"],
["stranger","見知らぬ人","n",3,"people","/ˈstreɪn.dʒər/","A stranger asked for help.","見知らぬ人が助けを求めた。"],
["partner","仲間","n",3,"people","/ˈpɑːt.nər/","She is a reliable partner.","彼女は頼れる仲間だ。"],
["leader","指導者","n",3,"people","/ˈliː.dər/","They chose a new leader.","彼らは新しい指導者を選んだ。"],
["customer","客","n",3,"people","/ˈkʌs.tə.mər/","The customer was satisfied.","その客は満足していた。"],
["colleague","同僚","n",4,"people","/ˈkɒl.iːɡ/","I asked a colleague for advice.","同僚に助言を求めた。"],
["audience","聴衆","n",4,"people","/ˈɔː.di.əns/","The audience fell silent.","聴衆は静まり返った。"],

/* ── 名詞: 場所 ─────────────────────────────────────────── */
["school","学校","n",1,"place","/skuːl/","I walk to school every day.","毎日歩いて学校へ行く。"],
["house","家","n",1,"place","/haʊs/","Their house is old.","彼らの家は古い。"],
["city","都市","n",1,"place","/ˈsɪt.i/","Tokyo is a big city.","東京は大きな都市だ。"],
["town","町","n",1,"place","/taʊn/","It is a quiet town.","静かな町だ。"],
["village","村","n",2,"place","/ˈvɪl.ɪdʒ/","A small village stands by the river.","川のそばに小さな村がある。"],
["station","駅","n",1,"place","/ˈsteɪ.ʃən/","Meet me at the station.","駅で会いましょう。"],
["hospital","病院","n",2,"place","/ˈhɒs.pɪ.təl/","She works at a hospital.","彼女は病院で働いている。"],
["library","図書館","n",2,"place","/ˈlaɪ.brər.i/","The library is quiet.","図書館は静かだ。"],
["market","市場","n",2,"place","/ˈmɑː.kɪt/","The market opens early.","市場は早く開く。"],
["office","事務所","n",2,"place","/ˈɒf.ɪs/","He left the office late.","彼は遅くに事務所を出た。"],
["airport","空港","n",2,"place","/ˈeə.pɔːt/","The airport was crowded.","空港は混雑していた。"],
["factory","工場","n",3,"place","/ˈfæk.tər.i/","The factory closed last year.","その工場は昨年閉鎖された。"],
["castle","城","n",3,"place","/ˈkɑː.səl/","The castle stands on a hill.","城は丘の上に立っている。"],
["temple","寺院","n",3,"place","/ˈtem.pəl/","An old temple stood there.","古い寺院がそこにあった。"],
["border","国境","n",4,"place","/ˈbɔː.dər/","They crossed the border at dawn.","彼らは夜明けに国境を越えた。"],

/* ── 名詞: 物 ─────────────────────────────────────────── */
["book","本","n",1,"object","/bʊk/","This book is interesting.","この本は面白い。"],
["letter","手紙","n",1,"object","/ˈlet.ər/","I got a letter from my friend.","友達から手紙が来た。"],
["door","ドア","n",1,"object","/dɔːr/","Close the door, please.","ドアを閉めてください。"],
["window","窓","n",1,"object","/ˈwɪn.dəʊ/","Open the window.","窓を開けて。"],
["chair","椅子","n",1,"object","/tʃeər/","Take that chair.","その椅子を使って。"],
["table","机","n",1,"object","/ˈteɪ.bəl/","Put it on the table.","机の上に置いて。"],
["key","鍵","n",1,"object","/kiː/","I lost my key.","鍵をなくした。"],
["clock","時計","n",1,"object","/klɒk/","The clock stopped.","時計が止まった。"],
["money","お金","n",1,"object","/ˈmʌn.i/","I don't have enough money.","お金が足りない。"],
["bag","かばん","n",1,"object","/bæɡ/","Her bag is heavy.","彼女のかばんは重い。"],
["shoe","靴","n",1,"object","/ʃuː/","These shoes are new.","この靴は新しい。"],
["map","地図","n",2,"object","/mæp/","Look at the map.","地図を見て。"],
["ring","指輪","n",2,"object","/rɪŋ/","She wore a silver ring.","彼女は銀の指輪をしていた。"],
["mirror","鏡","n",2,"object","/ˈmɪr.ər/","He looked in the mirror.","彼は鏡を見た。"],
["bridge","橋","n",2,"object","/brɪdʒ/","The bridge is closed.","その橋は閉鎖されている。"],
["tool","道具","n",3,"object","/tuːl/","Bring the right tool.","適切な道具を持ってきて。"],
["machine","機械","n",3,"object","/məˈʃiːn/","The machine stopped working.","機械が止まった。"],
["weapon","武器","n",4,"object","/ˈwep.ən/","They carried no weapon.","彼らは武器を持っていなかった。"],

/* ── 名詞: 時間 ─────────────────────────────────────────── */
["morning","朝","n",1,"time","/ˈmɔː.nɪŋ/","I run every morning.","毎朝走ります。"],
["night","夜","n",1,"time","/naɪt/","The stars are bright at night.","夜は星が明るい。"],
["day","日","n",1,"time","/deɪ/","It was a long day.","長い一日だった。"],
["week","週","n",1,"time","/wiːk/","See you next week.","また来週。"],
["year","年","n",1,"time","/jɪər/","She moved last year.","彼女は昨年引っ越した。"],
["hour","1時間","n",2,"time","/aʊər/","We waited an hour.","1時間待った。"],
["season","季節","n",2,"time","/ˈsiː.zən/","Spring is my favorite season.","春が一番好きな季節だ。"],
["future","未来","n",2,"time","/ˈfjuː.tʃər/","We can change the future.","未来は変えられる。"],
["past","過去","n",3,"time","/pɑːst/","Do not dwell on the past.","過去にとらわれるな。"],
["moment","瞬間","n",3,"time","/ˈməʊ.mənt/","Wait a moment.","少し待って。"],
["century","世紀","n",4,"time","/ˈsen.tʃər.i/","The building is a century old.","その建物は1世紀前のものだ。"],
["deadline","締め切り","n",4,"time","/ˈded.laɪn/","The deadline is tomorrow.","締め切りは明日だ。"],

/* ── 名詞: 抽象 ─────────────────────────────────────────── */
["reason","理由","n",2,"idea","/ˈriː.zən/","Tell me the reason.","理由を教えて。"],
["idea","考え","n",1,"idea","/aɪˈdɪə/","That is a good idea.","それは良い考えだ。"],
["question","質問","n",1,"idea","/ˈkwes.tʃən/","May I ask a question?","質問してもいいですか。"],
["answer","答え","n",1,"idea","/ˈɑːn.sər/","I know the answer.","答えを知っている。"],
["problem","問題","n",1,"idea","/ˈprɒb.ləm/","We solved the problem.","問題を解決した。"],
["danger","危険","n",2,"idea","/ˈdeɪn.dʒər/","The sign warns of danger.","標識が危険を知らせている。"],
["opinion","意見","n",2,"idea","/əˈpɪn.jən/","I'd like your opinion.","あなたの意見が聞きたい。"],
["challenge","挑戦","n",3,"idea","/ˈtʃæl.ɪndʒ/","This is a difficult challenge.","これは難しい挑戦だ。"],
["memory","記憶","n",3,"idea","/ˈmem.ər.i/","The memory faded.","その記憶は薄れた。"],
["purpose","目的","n",3,"idea","/ˈpɜː.pəs/","What is the purpose?","目的は何ですか。"],
["influence","影響","n",3,"idea","/ˈɪn.flu.əns/","Music has a strong influence on me.","音楽は私に強い影響を与える。"],
["evidence","証拠","n",4,"idea","/ˈev.ɪ.dəns/","There is no evidence.","証拠がない。"],
["consequence","招いた結末","n",4,"idea","/ˈkɒn.sɪ.kwəns/","Think about the consequence.","結果を考えなさい。"],
["assumption","前提","n",5,"idea","/əˈsʌmp.ʃən/","That assumption was wrong.","その前提は誤りだった。"],
["perspective","観点","n",5,"idea","/pəˈspek.tɪv/","Try another perspective.","別の観点で見てごらん。"],
["principle","原則","n",5,"idea","/ˈprɪn.sɪ.pəl/","He never breaks that principle.","彼はその原則を決して破らない。"],

/* ── 名詞: 感情 ─────────────────────────────────────────── */
["hope","希望","n",2,"emotion","/həʊp/","She never lost hope.","彼女は希望を失わなかった。"],
["fear","恐れ","n",3,"emotion","/fɪər/","He hid his fear.","彼は恐れを隠した。"],
["joy","喜び","n",3,"emotion","/dʒɔɪ/","Her face showed joy.","彼女の顔に喜びが表れた。"],
["anger","怒り","n",3,"emotion","/ˈæŋ.ɡər/","He controlled his anger.","彼は怒りを抑えた。"],
["sorrow","悲しみ","n",4,"emotion","/ˈsɒr.əʊ/","Deep sorrow filled the room.","深い悲しみが部屋を満たした。"],
["courage","勇気","n",4,"emotion","/ˈkʌr.ɪdʒ/","It takes courage to speak up.","声を上げるには勇気がいる。"],
["relief","安心","n",4,"emotion","/rɪˈliːf/","She sighed with relief.","彼女は安心してため息をついた。"],
["pride","誇り","n",4,"emotion","/praɪd/","He spoke with pride.","彼は誇りを持って話した。"],

/* ── 動詞: 移動 ─────────────────────────────────────────── */
["run","走る","v",1,"motion","/rʌn/","I run in the park.","公園で走ります。"],
["walk","歩く","v",1,"motion","/wɔːk/","We walked home.","私たちは歩いて帰った。"],
["jump","跳ぶ","v",1,"motion","/dʒʌmp/","He jumped over the fence.","彼は柵を跳び越えた。"],
["swim","泳ぐ","v",1,"motion","/swɪm/","She can swim well.","彼女は上手に泳げる。"],
["fly","飛ぶ","v",1,"motion","/flaɪ/","Birds fly south in winter.","鳥は冬に南へ飛ぶ。"],
["climb","登る","v",2,"motion","/klaɪm/","They climbed the hill.","彼らは丘を登った。"],
["fall","落ちる","v",2,"motion","/fɔːl/","Leaves fall in autumn.","秋には葉が落ちる。"],
["return","戻る","v",2,"motion","/rɪˈtɜːn/","I will return before dark.","暗くなる前に戻ります。"],
["escape","逃げる","v",2,"motion","/ɪˈskeɪp/","The thief tried to escape.","泥棒は逃げようとした。"],
["arrive","着く","v",2,"motion","/əˈraɪv/","We arrived late.","私たちは遅れて着いた。"],
["travel","旅行する","v",2,"motion","/ˈtræv.əl/","I want to travel abroad.","海外を旅行したい。"],
["chase","追う","v",3,"motion","/tʃeɪs/","The dog chased the ball.","犬がボールを追った。"],
["approach","近づく","v",4,"motion","/əˈprəʊtʃ/","A storm is approaching.","嵐が近づいている。"],
["retreat","退く","v",5,"motion","/rɪˈtriːt/","The army had to retreat.","軍は退かざるを得なかった。"],

/* ── 動詞: 発話・思考 ───────────────────────────────────── */
["say","言う","v",1,"speech","/seɪ/","What did he say?","彼は何と言ったの。"],
["ask","尋ねる","v",1,"speech","/ɑːsk/","May I ask something?","少し尋ねてもいい。"],
["listen","聞く","v",1,"speech","/ˈlɪs.ən/","Listen to this song.","この歌を聞いて。"],
["speak","話す","v",1,"speech","/spiːk/","She speaks three languages.","彼女は3か国語を話す。"],
["explain","説明する","v",2,"speech","/ɪkˈspleɪn/","Please explain it again.","もう一度説明して。"],
["agree","同意する","v",2,"speech","/əˈɡriː/","I agree with you.","あなたに同意します。"],
["refuse","断る","v",3,"speech","/rɪˈfjuːz/","He refused the offer.","彼は申し出を断った。"],
["suggest","提案する","v",3,"speech","/səˈdʒest/","She suggested a plan.","彼女は計画を提案した。"],
["admit","認める","v",4,"speech","/ədˈmɪt/","He admitted his mistake.","彼は誤りを認めた。"],
["declare","宣言する","v",5,"speech","/dɪˈkleər/","They declared victory.","彼らは勝利を宣言した。"],
["think","考える","v",1,"mind","/θɪŋk/","Let me think.","考えさせて。"],
["know","知る","v",1,"mind","/nəʊ/","I know the way.","道を知っています。"],
["learn","学ぶ","v",1,"mind","/lɜːn/","I want to learn English.","英語を学びたい。"],
["remember","思い出す","v",2,"mind","/rɪˈmem.bər/","I cannot remember his name.","彼の名前を思い出せない。"],
["forget","忘れる","v",2,"mind","/fəˈɡet/","Do not forget your key.","鍵を忘れないで。"],
["notice","気づく","v",2,"mind","/ˈnəʊ.tɪs/","Did you notice the change?","変化に気づいた。"],
["believe","信じる","v",2,"mind","/bɪˈliːv/","I believe you.","あなたを信じる。"],
["imagine","想像する","v",3,"mind","/ɪˈmædʒ.ɪn/","Imagine a quiet forest.","静かな森を想像して。"],
["decide","決める","v",2,"mind","/dɪˈsaɪd/","We decided to wait.","待つことに決めた。"],
["realize","はっと悟る","v",3,"mind","/ˈrɪə.laɪz/","He realized his error.","彼は誤りに気づいた。"],
["recognize","見分ける","v",3,"mind","/ˈrek.əɡ.naɪz/","I didn't recognize him.","彼だと分からなかった。"],
["consider","検討する","v",4,"mind","/kənˈsɪd.ər/","Consider every option.","すべての選択肢を検討して。"],
["assume","仮定する","v",5,"mind","/əˈsjuːm/","Do not assume too much.","決めつけすぎないで。"],

/* ── 動詞: 行為 ─────────────────────────────────────────── */
["make","作る","v",1,"action","/meɪk/","She made a cake.","彼女はケーキを作った。"],
["take","取る","v",1,"action","/teɪk/","Take one card.","カードを1枚取って。"],
["give","与える","v",1,"action","/ɡɪv/","Give me a hint.","ヒントをください。"],
["buy","買う","v",1,"action","/baɪ/","I want to buy a new bag.","新しいかばんを買いたい。"],
["sell","売る","v",2,"action","/sel/","They sell fresh fruit.","彼らは新鮮な果物を売る。"],
["open","開ける","v",1,"action","/ˈəʊ.pən/","Open the window, please.","窓を開けてください。"],
["close","閉じる","v",1,"action","/kləʊz/","Close your eyes.","目を閉じて。"],
["build","建てる","v",2,"action","/bɪld/","They built a bridge.","彼らは橋を建てた。"],
["break","壊す","v",2,"action","/breɪk/","Do not break it.","壊さないで。"],
["carry","運ぶ","v",2,"action","/ˈkær.i/","He carried the box.","彼は箱を運んだ。"],
["choose","選ぶ","v",2,"action","/tʃuːz/","Choose your favorite color.","好きな色を選んで。"],
["protect","守る","v",2,"action","/prəˈtekt/","This shield can protect you.","この盾があなたを守る。"],
["prepare","準備する","v",2,"action","/prɪˈpeər/","Let's prepare for the trip.","旅行の準備をしよう。"],
["repair","修理する","v",3,"action","/rɪˈpeər/","He repaired the roof.","彼は屋根を修理した。"],
["discover","発見する","v",2,"action","/dɪˈskʌv.ər/","They discovered a cave.","彼らは洞窟を発見した。"],
["improve","改善する","v",2,"action","/ɪmˈpruːv/","Practice will improve your English.","練習が英語を上達させる。"],
["increase","増やす","v",2,"action","/ɪnˈkriːs/","Prices increase every year.","値段は毎年上がる。"],
["reduce","減らす","v",2,"action","/rɪˈdjuːs/","We must reduce waste.","ごみを減らさなければ。"],
["achieve","達成する","v",3,"action","/əˈtʃiːv/","You can achieve your goal.","目標は達成できる。"],
["avoid","避ける","v",3,"action","/əˈvɔɪd/","Avoid the crowded road.","混んだ道は避けて。"],
["prevent","防ぐ","v",3,"action","/prɪˈvent/","This will prevent damage.","これが損傷を防ぐ。"],
["replace","取り替える","v",3,"action","/rɪˈpleɪs/","Replace the old part.","古い部品を交換して。"],
["overcome","克服する","v",4,"action","/ˌəʊ.vəˈkʌm/","We must overcome our fears.","恐れを克服しなければ。"],
["abandon","見捨てる","v",4,"action","/əˈbæn.dən/","Never abandon your friends.","友を見捨てるな。"],
["eliminate","撲滅する","v",4,"action","/ɪˈlɪm.ɪ.neɪt/","We need to eliminate the errors.","誤りを取り除く必要がある。"],
["expand","拡大する","v",4,"action","/ɪkˈspænd/","The company plans to expand.","会社は拡大を計画している。"],
["scrutinize","綿密に調べる","v",6,"action","/ˈskruː.tɪ.naɪz/","The lawyer scrutinized the contract.","弁護士は契約書を綿密に調べた。"],
["diminish","減少する","v",6,"action","/dɪˈmɪn.ɪʃ/","The pain will diminish soon.","痛みはすぐ和らぐ。"],

/* ── 形容詞: 大きさ・形 ─────────────────────────────────── */
["big","大きい","adj",1,"size","/bɪɡ/","That is a big dog.","あれは大きな犬だ。"],
["small","小さい","adj",1,"size","/smɔːl/","My room is very small.","私の部屋はとても小さい。"],
["long","長い","adj",1,"size","/lɒŋ/","It was a long day.","長い一日だった。"],
["short","短い","adj",1,"size","/ʃɔːt/","Give a short answer.","短く答えて。"],
["wide","広い","adj",2,"size","/waɪd/","The river is wide here.","この辺りの川は広い。"],
["narrow","狭い","adj",2,"size","/ˈnær.əʊ/","The path is narrow.","その道は狭い。"],
["deep","深い","adj",2,"size","/diːp/","The lake is deep.","その湖は深い。"],
["thick","厚い","adj",3,"size","/θɪk/","He wore a thick coat.","彼は厚いコートを着ていた。"],
["thin","薄い","adj",3,"size","/θɪn/","The ice is thin.","氷が薄い。"],
["enormous","並外れて大きい","adj",4,"size","/ɪˈnɔː.məs/","An enormous rock blocked the road.","巨大な岩が道を塞いだ。"],

/* ── 形容詞: 性質 ─────────────────────────────────────── */
["good","良い","adj",1,"quality","/ɡʊd/","This is a good plan.","これは良い計画だ。"],
["bad","悪い","adj",1,"quality","/bæd/","The weather is bad.","天気が悪い。"],
["new","新しい","adj",1,"quality","/njuː/","I bought a new bag.","新しいかばんを買った。"],
["old","古い","adj",1,"quality","/əʊld/","This is an old map.","これは古い地図だ。"],
["easy","簡単な","adj",1,"quality","/ˈiː.zi/","The test was easy.","試験は簡単だった。"],
["difficult","難しい","adj",2,"quality","/ˈdɪf.ɪ.kəlt/","This question is difficult.","この問題は難しい。"],
["important","重要な","adj",2,"quality","/ɪmˈpɔː.tənt/","This is an important point.","これは重要な点だ。"],
["simple","単純な","adj",2,"quality","/ˈsɪm.pəl/","Keep it simple.","単純にしておいて。"],
["strange","奇妙な","adj",2,"quality","/streɪndʒ/","A strange sound came from outside.","外から奇妙な音がした。"],
["safe","安全な","adj",2,"quality","/seɪf/","This road is safe.","この道は安全だ。"],
["dangerous","危険な","adj",2,"quality","/ˈdeɪn.dʒər.əs/","That cliff is dangerous.","あの崖は危険だ。"],
["useful","役に立つ","adj",2,"quality","/ˈjuːs.fəl/","This tool is useful.","この道具は役に立つ。"],
["common","一般的な","adj",3,"quality","/ˈkɒm.ən/","That is a common mistake.","それはよくある間違いだ。"],
["rare","まれな","adj",3,"quality","/reər/","This bird is rare.","この鳥はまれだ。"],
["obvious","明らかな","adj",3,"quality","/ˈɒb.vi.əs/","The answer is obvious.","答えは明らかだ。"],
["essential","不可欠な","adj",4,"quality","/ɪˈsen.ʃəl/","Water is essential for life.","水は生命に不可欠だ。"],
["reliable","信頼できる","adj",4,"quality","/rɪˈlaɪ.ə.bəl/","She is a reliable partner.","彼女は信頼できる仲間だ。"],
["sufficient","事足りる","adj",4,"quality","/səˈfɪʃ.ənt/","We have sufficient food.","食料は十分ある。"],
["ambiguous","曖昧な","adj",5,"quality","/æmˈbɪɡ.ju.əs/","The message was ambiguous.","その伝言は曖昧だった。"],
["inevitable","避けられない","adj",5,"quality","/ɪnˈev.ɪ.tə.bəl/","Change is inevitable.","変化は避けられない。"],
["arbitrary","恣意的な","adj",6,"quality","/ˈɑː.bɪ.trə.ri/","The rule seems arbitrary.","その規則は恣意的に見える。"],
["prevalent","広く行き渡った","adj",6,"quality","/ˈprev.əl.ənt/","This custom is prevalent here.","この習慣はここで広く行き渡っている。"],
["unprecedented","前例のない","adj",6,"quality","/ʌnˈpres.ɪ.den.tɪd/","The team achieved unprecedented success.","チームは前例のない成功を収めた。"],

/* ── 形容詞: 感情・状態 ─────────────────────────────────── */
["happy","幸せな","adj",1,"feeling","/ˈhæp.i/","She looks happy today.","今日の彼女は幸せそうだ。"],
["sad","悲しい","adj",1,"feeling","/sæd/","He felt sad.","彼は悲しかった。"],
["angry","怒った","adj",1,"feeling","/ˈæŋ.ɡri/","She was angry with me.","彼女は私に怒っていた。"],
["tired","疲れた","adj",1,"feeling","/taɪəd/","I am tired today.","今日は疲れた。"],
["hungry","空腹の","adj",1,"feeling","/ˈhʌŋ.ɡri/","I'm hungry. Let's eat.","おなかがすいた。食べよう。"],
["afraid","恐れて","adj",2,"feeling","/əˈfreɪd/","Do not be afraid.","恐れないで。"],
["calm","穏やかな","adj",2,"feeling","/kɑːm/","Stay calm.","落ち着いて。"],
["quiet","静かな","adj",1,"feeling","/ˈkwaɪ.ət/","The library is quiet.","図書館は静かだ。"],
["nervous","緊張した","adj",3,"feeling","/ˈnɜː.vəs/","He felt nervous before the test.","彼は試験前に緊張していた。"],
["curious","好奇心の強い","adj",3,"feeling","/ˈkjʊə.ri.əs/","Children are curious.","子どもは好奇心が強い。"],
["confident","自信のある","adj",3,"feeling","/ˈkɒn.fɪ.dənt/","She is confident about the test.","彼女は試験に自信がある。"],
["brave","勇敢な","adj",2,"feeling","/breɪv/","A brave knight entered the cave.","勇敢な騎士が洞窟に入った。"],
["generous","気前のよい","adj",4,"feeling","/ˈdʒen.ər.əs/","He is generous to everyone.","彼は誰にでも気前がよい。"],
["reluctant","気が進まない","adj",5,"feeling","/rɪˈlʌk.tənt/","He was reluctant to leave.","彼は去るのを渋った。"],
["resilient","回復力のある","adj",6,"feeling","/rɪˈzɪl.i.ənt/","Children are surprisingly resilient.","子どもは驚くほど回復力がある。"],

/* ── 副詞 ─────────────────────────────────────────────── */
["always","いつも","adv",1,"freq","/ˈɔːl.weɪz/","She is always early.","彼女はいつも早い。"],
["never","決して〜ない","adv",1,"freq","/ˈnev.ər/","He never gives up.","彼は決して諦めない。"],
["often","しばしば","adv",2,"freq","/ˈɒf.ən/","We often meet here.","私たちはよくここで会う。"],
["sometimes","時々","adv",1,"freq","/ˈsʌm.taɪmz/","Sometimes I walk home.","時々歩いて帰る。"],
["rarely","めったに〜ない","adv",3,"freq","/ˈreə.li/","He rarely speaks.","彼はめったに話さない。"],
["quickly","素早く","adv",2,"manner","/ˈkwɪk.li/","She answered quickly.","彼女は素早く答えた。"],
["slowly","ゆっくりと","adv",1,"manner","/ˈsləʊ.li/","Speak slowly, please.","ゆっくり話してください。"],
["carefully","注意深く","adv",2,"manner","/ˈkeə.fəl.i/","Read the note carefully.","注意深くメモを読んで。"],
["suddenly","突然に","adv",2,"manner","/ˈsʌd.ən.li/","Suddenly the light went out.","突然明かりが消えた。"],
["gradually","徐々に","adv",3,"manner","/ˈɡrædʒ.u.ə.li/","The sky gradually turned red.","空は徐々に赤くなった。"],
["barely","かろうじて","adv",4,"manner","/ˈbeə.li/","I barely made it.","かろうじて間に合った。"],
["deliberately","意図的に","adv",5,"manner","/dɪˈlɪb.ər.ət.li/","He did it deliberately.","彼は意図的にそれをした。"]
];
