/* WORD QUEST RUN — word data (window.WORDS)
   後から追加しやすいよう独立ファイル化。
   形式: { w:英単語, p:発音, a:正しい日本語訳, x:[誤答の日本語×3], d:難易度1-4, e:例文 }
   難易度 d: 1=初級 EASY / 2=中級 NORMAL / 3=上級 HARD / 4=MASTER */
window.WORDS = [
  { w: "apple", p: "/ˈæp.əl/", a: "りんご", x: ["机", "指輪", "手紙"], d: 1, e: "I eat an apple every morning." },
  { w: "book", p: "/bʊk/", a: "本", x: ["鳥", "海", "橋"], d: 1, e: "This book is very interesting." },
  { w: "happy", p: "/ˈhæp.i/", a: "幸せな", x: ["静かな", "重い", "短い"], d: 1, e: "She looks happy today." },
  { w: "run", p: "/rʌn/", a: "走る", x: ["歌う", "眠る", "書く"], d: 1, e: "I run in the park every Sunday." },
  { w: "water", p: "/ˈwɔː.tər/", a: "水", x: ["火", "風", "土"], d: 1, e: "Please drink some water." },
  { w: "friend", p: "/frend/", a: "友達", x: ["先生", "医者", "客"], d: 1, e: "He is my best friend." },
  { w: "strong", p: "/strɔːŋ/", a: "強い", x: ["薄い", "遅い", "狭い"], d: 1, e: "The hero is very strong." },
  { w: "night", p: "/naɪt/", a: "夜", x: ["朝", "冬", "町"], d: 1, e: "The stars are bright at night." },
  { w: "buy", p: "/baɪ/", a: "買う", x: ["投げる", "洗う", "貸す"], d: 1, e: "I want to buy a new bag." },
  { w: "listen", p: "/ˈlɪs.ən/", a: "聞く", x: ["触る", "数える", "押す"], d: 1, e: "Listen to this song." },
  { w: "small", p: "/smɔːl/", a: "小さい", x: ["明るい", "甘い", "固い"], d: 1, e: "My room is very small." },
  { w: "money", p: "/ˈmʌn.i/", a: "お金", x: ["時計", "地図", "鍵"], d: 1, e: "I don't have enough money." },
  { w: "open", p: "/ˈəʊ.pən/", a: "開ける", x: ["埋める", "混ぜる", "曲げる"], d: 1, e: "Open the window, please." },
  { w: "school", p: "/skuːl/", a: "学校", x: ["台所", "工場", "空港"], d: 1, e: "I walk to school every day." },
  { w: "hungry", p: "/ˈhʌŋ.ɡri/", a: "空腹の", x: ["眠い", "退屈な", "有名な"], d: 1, e: "I'm hungry. Let's eat lunch." },
  { w: "answer", p: "/ˈɑːn.sər/", a: "答える", x: ["並ぶ", "落ちる", "泳ぐ"], d: 1, e: "Please answer my question." },
  { w: "city", p: "/ˈsɪt.i/", a: "都市", x: ["森", "谷", "島"], d: 1, e: "Tokyo is a big city." },
  { w: "beautiful", p: "/ˈbjuː.tɪ.fəl/", a: "美しい", x: ["寒い", "安い", "危ない"], d: 1, e: "What a beautiful sunset!" },
  { w: "learn", p: "/lɜːn/", a: "学ぶ", x: ["借りる", "捨てる", "叫ぶ"], d: 1, e: "I want to learn English." },
  { w: "letter", p: "/ˈlet.ər/", a: "手紙", x: ["枕", "皿", "靴"], d: 1, e: "I got a letter from my friend." },

  /* ── d2 / NORMAL ─────────────────────────────── */
  { w: "travel", p: "/ˈtræv.əl/", a: "旅行する", x: ["料理する", "修理する", "掃除する"], d: 2, e: "I want to travel abroad." },
  { w: "choose", p: "/tʃuːz/", a: "選ぶ", x: ["隠す", "壊す", "運ぶ"], d: 2, e: "Choose your favorite color." },
  { w: "future", p: "/ˈfjuː.tʃər/", a: "未来", x: ["過去", "記憶", "距離"], d: 2, e: "We can change the future." },
  { w: "improve", p: "/ɪmˈpruːv/", a: "改善する", x: ["拒否する", "比較する", "延期する"], d: 2, e: "Practice will improve your English." },
  { w: "protect", p: "/prəˈtekt/", a: "守る", x: ["攻撃する", "捨てる", "交換する"], d: 2, e: "This shield can protect you." },
  { w: "discover", p: "/dɪˈskʌv.ər/", a: "発見する", x: ["説明する", "想像する", "輸入する"], d: 2, e: "They discovered a hidden cave." },
  { w: "reason", p: "/ˈriː.zən/", a: "理由", x: ["感情", "順番", "習慣"], d: 2, e: "Tell me the reason for your choice." },
  { w: "prepare", p: "/prɪˈpeər/", a: "準備する", x: ["諦める", "訪ねる", "遅れる"], d: 2, e: "Let's prepare for the trip." },
  { w: "danger", p: "/ˈdeɪn.dʒər/", a: "危険", x: ["幸運", "自由", "沈黙"], d: 2, e: "The sign warns of danger." },
  { w: "increase", p: "/ɪnˈkriːs/", a: "増える", x: ["消える", "止まる", "溶ける"], d: 2, e: "Prices increase every year." },
  { w: "quiet", p: "/ˈkwaɪ.ət/", a: "静かな", x: ["新鮮な", "正直な", "有能な"], d: 2, e: "The library is very quiet." },
  { w: "return", p: "/rɪˈtɜːn/", a: "戻る", x: ["育つ", "働く", "見つめる"], d: 2, e: "I will return before dark." },
  { w: "difficult", p: "/ˈdɪf.ɪ.kəlt/", a: "難しい", x: ["柔らかい", "騒がしい", "空っぽの"], d: 2, e: "This question is too difficult." },
  { w: "village", p: "/ˈvɪl.ɪdʒ/", a: "村", x: ["城", "港", "宿"], d: 2, e: "A small village stands by the river." },
  { w: "notice", p: "/ˈnəʊ.tɪs/", a: "気づく", x: ["黙る", "祈る", "追う"], d: 2, e: "Did you notice the change?" },
  { w: "reduce", p: "/rɪˈdjuːs/", a: "減らす", x: ["集める", "続ける", "混ぜる"], d: 2, e: "We must reduce plastic waste." },
  { w: "opinion", p: "/əˈpɪn.jən/", a: "意見", x: ["証拠", "結果", "手順"], d: 2, e: "I'd like to hear your opinion." },
  { w: "silent", p: "/ˈsaɪ.lənt/", a: "無言の", x: ["派手な", "健康な", "斜めの"], d: 2, e: "He stayed silent for a while." },
  { w: "escape", p: "/ɪˈskeɪp/", a: "逃げる", x: ["戦う", "眠る", "祝う"], d: 2, e: "The thief tried to escape." },
  { w: "brave", p: "/breɪv/", a: "勇敢な", x: ["正確な", "退屈な", "豊かな"], d: 2, e: "A brave knight entered the cave." },

  /* ── d3 / HARD ───────────────────────────────── */
  { w: "ancient", p: "/ˈeɪn.ʃənt/", a: "古代の", x: ["現代の", "巨大な", "透明な"], d: 3, e: "We found an ancient temple." },
  { w: "challenge", p: "/ˈtʃæl.ɪndʒ/", a: "挑戦", x: ["安心", "習慣", "約束"], d: 3, e: "This is a difficult challenge." },
  { w: "achieve", p: "/əˈtʃiːv/", a: "達成する", x: ["避ける", "依頼する", "借りる"], d: 3, e: "You can achieve your goal." },
  { w: "essential", p: "/ɪˈsen.ʃəl/", a: "不可欠な", x: ["一時的な", "偶然の", "平凡な"], d: 3, e: "Water is essential for life." },
  { w: "overcome", p: "/ˌəʊ.vəˈkʌm/", a: "克服する", x: ["観察する", "延期する", "区別する"], d: 3, e: "We must overcome our fears." },
  { w: "recognize", p: "/ˈrek.əɡ.naɪz/", a: "見分ける", x: ["組み立てる", "翻訳する", "包む"], d: 3, e: "I didn't recognize him at first." },
  { w: "obvious", p: "/ˈɒb.vi.əs/", a: "明らかな", x: ["曖昧な", "貴重な", "厳しい"], d: 3, e: "The answer is obvious." },
  { w: "influence", p: "/ˈɪn.flu.əns/", a: "影響", x: ["費用", "境界", "義務"], d: 3, e: "Music has a strong influence on me." },
  { w: "gradually", p: "/ˈɡrædʒ.u.ə.li/", a: "徐々に", x: ["突然に", "偶然に", "頻繁に"], d: 3, e: "The sky gradually turned red." },
  { w: "reliable", p: "/rɪˈlaɪ.ə.bəl/", a: "信頼できる", x: ["利用できる", "分解できる", "交換できる"], d: 3, e: "She is a reliable partner." },
  { w: "consequence", p: "/ˈkɒn.sɪ.kwəns/", a: "結果", x: ["目的", "前提", "手段"], d: 3, e: "Think about the consequence of your action." },
  { w: "eliminate", p: "/ɪˈlɪm.ɪ.neɪt/", a: "取り除く", x: ["受け入れる", "積み重ねる", "呼び戻す"], d: 3, e: "We need to eliminate the errors." },
  { w: "sufficient", p: "/səˈfɪʃ.ənt/", a: "十分な", x: ["不足した", "余分な", "強引な"], d: 3, e: "We have sufficient food for a week." },
  { w: "abandon", p: "/əˈbæn.dən/", a: "見捨てる", x: ["引き受ける", "取り戻す", "呼び寄せる"], d: 3, e: "Never abandon your friends." },
  { w: "generous", p: "/ˈdʒen.ər.əs/", a: "気前のよい", x: ["用心深い", "せっかちな", "頑固な"], d: 3, e: "He is generous to everyone." },
  { w: "confident", p: "/ˈkɒn.fɪ.dənt/", a: "自信のある", x: ["謙虚な", "無関心な", "疑い深い"], d: 3, e: "She is confident about the test." },
  { w: "expand", p: "/ɪkˈspænd/", a: "拡大する", x: ["縮小する", "分類する", "停止する"], d: 3, e: "The company plans to expand overseas." },
  { w: "curious", p: "/ˈkjʊə.ri.əs/", a: "好奇心の強い", x: ["用心深い", "疑い深い", "冷淡な"], d: 3, e: "Children are curious about everything." },

  /* ── d4 / MASTER ─────────────────────────────── */
  { w: "reluctant", p: "/rɪˈlʌk.tənt/", a: "気が進まない", x: ["誇らしい", "素早い", "寛大な"], d: 4, e: "He was reluctant to leave." },
  { w: "inevitable", p: "/ɪnˈev.ɪ.tə.bəl/", a: "避けられない", x: ["予測できない", "理解しやすい", "価値のない"], d: 4, e: "Change is inevitable." },
  { w: "meticulous", p: "/məˈtɪk.jə.ləs/", a: "細心の", x: ["乱暴な", "無関心な", "単純な"], d: 4, e: "She is meticulous about details." },
  { w: "ambiguous", p: "/æmˈbɪɡ.ju.əs/", a: "曖昧な", x: ["明白な", "永続的な", "実用的な"], d: 4, e: "The message was ambiguous." },
  { w: "profound", p: "/prəˈfaʊnd/", a: "深遠な", x: ["表面的な", "一方的な", "断片的な"], d: 4, e: "His speech had a profound meaning." },
  { w: "diminish", p: "/dɪˈmɪn.ɪʃ/", a: "減少する", x: ["急増する", "変質する", "分岐する"], d: 4, e: "The pain will diminish soon." },
  { w: "compelling", p: "/kəmˈpel.ɪŋ/", a: "説得力のある", x: ["回りくどい", "行き当たりばったりの", "取るに足らない"], d: 4, e: "She gave a compelling argument." },
  { w: "scrutinize", p: "/ˈskruː.tɪ.naɪz/", a: "綿密に調べる", x: ["おおまかに見積もる", "大げさに伝える", "巧みに言い換える"], d: 4, e: "The lawyer scrutinized the contract." },
  { w: "resilient", p: "/rɪˈzɪl.i.ənt/", a: "回復力のある", x: ["壊れやすい", "移り気な", "融通の利かない"], d: 4, e: "Children are surprisingly resilient." },
  { w: "arbitrary", p: "/ˈɑː.bɪ.trə.ri/", a: "恣意的な", x: ["体系的な", "自発的な", "相互的な"], d: 4, e: "The rule seems completely arbitrary." },
  { w: "articulate", p: "/ɑːˈtɪk.jə.leɪt/", a: "明確に述べる", x: ["遠回しに触れる", "適当に受け流す", "強引に打ち切る"], d: 4, e: "He can articulate his ideas clearly." },
  { w: "prevalent", p: "/ˈprev.əl.ənt/", a: "広く行き渡った", x: ["ごく限られた", "時代遅れの", "極めて高価な"], d: 4, e: "This custom is prevalent in the north." },
  { w: "tedious", p: "/ˈtiː.di.əs/", a: "退屈な", x: ["刺激的な", "手軽な", "格式ばった"], d: 4, e: "Copying the data was a tedious task." },
  { w: "unprecedented", p: "/ʌnˈpres.ɪ.den.tɪd/", a: "前例のない", x: ["申し分のない", "見返りのない", "抑えようのない"], d: 4, e: "The team achieved unprecedented success." },
];
